services:
  redis-cache:
    image: redis:8.8.0
    container_name: redis-cache
    command:
      [
        "redis-server",
        "--save",
        "",
        "--appendonly",
        "no",
        "--maxmemory",
        "256mb",
        "--maxmemory-policy",
        "allkeys-lru",
      ]
    networks:
      - app-nest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis-session:
    image: redis:8.8.0
    container_name: redis-session
    command: ["redis-server", "--maxmemory-policy", "noeviction"]
    volumes:
      - /home/carlos/data/redis:/data
    networks:
      - app-nest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /home/carlos/data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-nest
  app:
    build:
      context: .
      args:
        - PORT=${PORT}
    container_name: app
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      postgres:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      redis-session:
        condition: service_healthy
    networks:
      - app-nest
networks:
  app-nest:
    driver: bridge
